trading_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: postgres_bi
      port: 5432
      user: postgres
      password: postgres
      dbname: postgres
      schema: public